2018-01-21 12:31:30,127 - ERROR || apscheduler.executors.default - run_job - ||Job "基金查询_预估值_test (trigger: cron[second='0/30'], next run at: 2018-01-21 12:32:00 CST)" raised an exception 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/yanghuang/WeChatProject/jijing-server/scrapy/FundationGrowShedule.py", line 30, in scrapAndSaveFinMsg
    time_9_30 = time.strptime("09:30", "hh:mm")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '09:30' does not match format 'hh:mm'
2018-01-21 12:33:30,071 - ERROR || apscheduler.executors.default - run_job - ||Job "基金查询_预估值_test (trigger: cron[second='0/30'], next run at: 2018-01-21 12:34:00 CST)" raised an exception 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/yanghuang/WeChatProject/jijing-server/scrapy/FundationGrowShedule.py", line 32, in scrapAndSaveFinMsg
    if now_time < time_9_30 or now_time > time_13_00:
TypeError: '<' not supported between instances of 'float' and 'time.struct_time'
